// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gamersdomain.Server.Data;

#nullable disable

namespace gamersdomain.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231029002608_InitialProducts")]
    partial class InitialProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("gamersdomain.Shared.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Test product #1! The finest test product known to man!",
                            Name = "Test Product #1",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Test product #2! The second finest test product known to man!",
                            Name = "Test Product #2",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Test product #3! We don't really like to talk about test product #3. Gary made that one. Gary was a WEIRD dude...",
                            Name = "Test Product #3",
                            Price = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
