// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gamersdomain.Server.Data;

#nullable disable

namespace gamersdomain.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231107224552_ExtraSeedData")]
    partial class ExtraSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("gamersdomain.Shared.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Computers",
                            Url = "computers"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Keyboards",
                            Url = "keyboards"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Mice",
                            Url = "mice"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Headsets",
                            Url = "headsets"
                        });
                });

            modelBuilder.Entity("gamersdomain.Shared.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeaturedProduct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Test product #1! The finest test product known to man!",
                            ImageUrl = "/images/computers/comp1.png",
                            IsFeaturedProduct = false,
                            Name = "Test Product #1",
                            Price = 1499.99m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "Test product #2! The second finest test product known to man!",
                            ImageUrl = "/images/mice/m1.png",
                            IsFeaturedProduct = false,
                            Name = "Test Product #2",
                            Price = 149.99m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 4,
                            Description = "Test product #3! We don't really like to talk about test product #3. Gary made that one. Gary was a WEIRD dude...",
                            ImageUrl = "/images/headsets/hs1.png",
                            IsFeaturedProduct = false,
                            Name = "Test Product #3",
                            Price = 199.99m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 3,
                            Description = "Test Product #4! The fourth finest product known to man!",
                            ImageUrl = "/images/keyboards/kb1.png",
                            IsFeaturedProduct = false,
                            Name = "Test Product #4",
                            Price = 74.99m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "An incredibly powerful gaming system!",
                            ImageUrl = "/images/computers/comp2.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Elite Z-92",
                            Price = 2499.99m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Description = "An incredibly powerful gaming system!",
                            ImageUrl = "/images/computers/comp3.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Elite Z-150",
                            Price = 3299.99m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "An incredibly powerful gaming system!",
                            ImageUrl = "/images/computers/comp4.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Supercharger XL-7",
                            Price = 999.99m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "A stylish mouse for all your gaming needs!",
                            ImageUrl = "/images/mice/m2.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Elite 'Snow Viper'",
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Description = "A stylish mouse for all your gaming needs!",
                            ImageUrl = "/images/mice/m3.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Elite 'Sandstorm'",
                            Price = 69.99m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            Description = "A stylish mouse for all your gaming needs!",
                            ImageUrl = "/images/mice/m4.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Elite 'Leviathan'",
                            Price = 119.99m
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Description = "A stylish keyboard for all your gaming needs!",
                            ImageUrl = "/images/keyboards/kb2.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Dominion 'Minion'",
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Description = "A stylish keyboard for all your gaming needs!",
                            ImageUrl = "/images/keyboards/kb3.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Dominion 'Afterburner'",
                            Price = 219.99m
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3,
                            Description = "A stylish keyboard for all your gaming needs!",
                            ImageUrl = "/images/keyboards/kb4.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Dominion 'Bobcat'",
                            Price = 19.99m
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4,
                            Description = "A stylish headset for all your gaming needs!",
                            ImageUrl = "/images/headsets/hs2.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Dominion 'Sunstorm'",
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4,
                            Description = "A stylish headset for all your gaming needs!",
                            ImageUrl = "/images/headsets/hs3.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Dominion 'Honeybadger'",
                            Price = 199.99m
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Description = "A stylish headset for all your gaming needs!",
                            ImageUrl = "/images/headsets/hs4.png",
                            IsFeaturedProduct = false,
                            Name = "Gamers Dominion 'Glory'",
                            Price = 249.99m
                        });
                });

            modelBuilder.Entity("gamersdomain.Shared.Product", b =>
                {
                    b.HasOne("gamersdomain.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
