// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gamersdomain.Server.Data;

#nullable disable

namespace gamersdomain.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231103003547_UpdateCategories")]
    partial class UpdateCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("gamersdomain.Shared.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Computers",
                            Url = "computers"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Keyboards",
                            Url = "keyboards"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Mice",
                            Url = "mice"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Headsets",
                            Url = "headsets"
                        });
                });

            modelBuilder.Entity("gamersdomain.Shared.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeaturedProduct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Test product #1! The finest test product known to man!",
                            ImageUrl = "/images/computers/comp1.png",
                            IsFeaturedProduct = false,
                            Name = "Test Product #1",
                            Price = 1499.99m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "Test product #2! The second finest test product known to man!",
                            ImageUrl = "/images/mice/m3.png",
                            IsFeaturedProduct = false,
                            Name = "Test Product #2",
                            Price = 149.99m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 4,
                            Description = "Test product #3! We don't really like to talk about test product #3. Gary made that one. Gary was a WEIRD dude...",
                            ImageUrl = "/images/headsets/hs6.png",
                            IsFeaturedProduct = false,
                            Name = "Test Product #3",
                            Price = 199.99m
                        });
                });

            modelBuilder.Entity("gamersdomain.Shared.Product", b =>
                {
                    b.HasOne("gamersdomain.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
